/*
 * This file is generated by jOOQ.
 */
package io.miscellanea.madison.dal.jooq;


import io.miscellanea.madison.dal.jooq.tables.Author;
import io.miscellanea.madison.dal.jooq.tables.AuthorDocument;
import io.miscellanea.madison.dal.jooq.tables.Document;
import io.miscellanea.madison.dal.jooq.tables.Identifiers;


/**
 * Convenience access to all tables in catalog.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>catalog.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>catalog.author_document</code>.
     */
    public static final AuthorDocument AUTHOR_DOCUMENT = AuthorDocument.AUTHOR_DOCUMENT;

    /**
     * The table <code>catalog.document</code>.
     */
    public static final Document DOCUMENT = Document.DOCUMENT;

    /**
     * The table <code>catalog.identifiers</code>.
     */
    public static final Identifiers IDENTIFIERS = Identifiers.IDENTIFIERS;
}
