/*
 * This file is generated by jOOQ.
 */
package io.miscellanea.madison.dal.jooq.tables;


import io.miscellanea.madison.dal.jooq.Catalog;
import io.miscellanea.madison.dal.jooq.Keys;
import io.miscellanea.madison.dal.jooq.tables.records.DocumentRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Document extends TableImpl<DocumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>catalog.document</code>
     */
    public static final Document DOCUMENT = new Document();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocumentRecord> getRecordType() {
        return DocumentRecord.class;
    }

    /**
     * The column <code>catalog.document.id</code>.
     */
    public final TableField<DocumentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>catalog.document.title</code>.
     */
    public final TableField<DocumentRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>catalog.document.page_count</code>.
     */
    public final TableField<DocumentRecord, Integer> PAGE_COUNT = createField(DSL.name("page_count"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>catalog.document.fingerprint</code>.
     */
    public final TableField<DocumentRecord, String> FINGERPRINT = createField(DSL.name("fingerprint"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>catalog.document.content_type</code>.
     */
    public final TableField<DocumentRecord, String> CONTENT_TYPE = createField(DSL.name("content_type"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>catalog.document.isbn10</code>.
     */
    public final TableField<DocumentRecord, String> ISBN10 = createField(DSL.name("isbn10"), SQLDataType.CHAR(10), this, "");

    /**
     * The column <code>catalog.document.isbn13</code>.
     */
    public final TableField<DocumentRecord, String> ISBN13 = createField(DSL.name("isbn13"), SQLDataType.CHAR(13), this, "");

    private Document(Name alias, Table<DocumentRecord> aliased) {
        this(alias, aliased, null);
    }

    private Document(Name alias, Table<DocumentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>catalog.document</code> table reference
     */
    public Document(String alias) {
        this(DSL.name(alias), DOCUMENT);
    }

    /**
     * Create an aliased <code>catalog.document</code> table reference
     */
    public Document(Name alias) {
        this(alias, DOCUMENT);
    }

    /**
     * Create a <code>catalog.document</code> table reference
     */
    public Document() {
        this(DSL.name("document"), null);
    }

    public <O extends Record> Document(Table<O> child, ForeignKey<O, DocumentRecord> key) {
        super(child, key, DOCUMENT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Catalog.CATALOG;
    }

    @Override
    public Identity<DocumentRecord, Long> getIdentity() {
        return (Identity<DocumentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DocumentRecord> getPrimaryKey() {
        return Keys.DOCUMENT_PKEY;
    }

    @Override
    public List<UniqueKey<DocumentRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.DOCUMENT_FINGERPRINT_KEY);
    }

    @Override
    public Document as(String alias) {
        return new Document(DSL.name(alias), this);
    }

    @Override
    public Document as(Name alias) {
        return new Document(alias, this);
    }

    @Override
    public Document as(Table<?> alias) {
        return new Document(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Document rename(String name) {
        return new Document(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Document rename(Name name) {
        return new Document(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Document rename(Table<?> name) {
        return new Document(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, Integer, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super String, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super String, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
