version: "3.4"
services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: madison
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ${PG_DATA_BIND_DIR}:/var/lib/postgresql/data

  broker:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - ${RABBIT_BROKER_PORT}:5672
      - ${RABBIT_MGMT_PORT}:15672
    volumes:
      - ${RABBIT_DATA_DIR}:/var/lib/rabbitmq/mnesia

  tika:
    #image: ghcr.io/paperless-ngx/tika:latest
    image: apache/tika:latest
    restart: unless-stopped
    ports:
      - ${TIKA_PORT}:9998

  gotenberg:
    image: gotenberg/gotenberg:7.6
    restart: unless-stopped
    #The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
