/*
 * This file is generated by jOOQ.
 */
package io.miscellanea.madison.dal.jooq.tables.records;


import io.miscellanea.madison.dal.jooq.tables.Document;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentRecord extends UpdatableRecordImpl<DocumentRecord> implements Record4<Long, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>catalog.document.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>catalog.document.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>catalog.document.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>catalog.document.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>catalog.document.page_count</code>.
     */
    public void setPageCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>catalog.document.page_count</code>.
     */
    public Integer getPageCount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>catalog.document.fingerprint</code>.
     */
    public void setFingerprint(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>catalog.document.fingerprint</code>.
     */
    public String getFingerprint() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Document.DOCUMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return Document.DOCUMENT.TITLE;
    }

    @Override
    public Field<Integer> field3() {
        return Document.DOCUMENT.PAGE_COUNT;
    }

    @Override
    public Field<String> field4() {
        return Document.DOCUMENT.FINGERPRINT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public Integer component3() {
        return getPageCount();
    }

    @Override
    public String component4() {
        return getFingerprint();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public Integer value3() {
        return getPageCount();
    }

    @Override
    public String value4() {
        return getFingerprint();
    }

    @Override
    public DocumentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DocumentRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public DocumentRecord value3(Integer value) {
        setPageCount(value);
        return this;
    }

    @Override
    public DocumentRecord value4(String value) {
        setFingerprint(value);
        return this;
    }

    @Override
    public DocumentRecord values(Long value1, String value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocumentRecord
     */
    public DocumentRecord() {
        super(Document.DOCUMENT);
    }

    /**
     * Create a detached, initialised DocumentRecord
     */
    public DocumentRecord(Long id, String title, Integer pageCount, String fingerprint) {
        super(Document.DOCUMENT);

        setId(id);
        setTitle(title);
        setPageCount(pageCount);
        setFingerprint(fingerprint);
    }
}
